name: Create PKG torrent
on:
  workflow_dispatch:
    inputs:
      name:
        description: Name
        required: true
        default: ' PS3'
      comment:
        description: Comment
        required: true
        default: ' US PS3 PSN PKG NPS by AnimMouse'
      url:
        description: PKG URL
        required: true
      piece_size:
        description: Piece Size. Use auto for automatic calculation.
        required: true
        default: auto
      protocol_version:
        description: BitTorrent Protocol version 1, 2, or hybrid
        required: true
        default: 1
        
jobs:
  create_torrent:
    runs-on: ubuntu-latest
    steps:
      - name: Install torrenttools
        run: |
          sudo add-apt-repository ppa:fbdtemme/torrenttools
          sudo apt-get update
          sudo apt-get install torrenttools
          
      - name: Get file name from URL
        id: file_name
        run: echo "::set-output name=file_name::$(basename ${{ github.event.inputs.url }})"
        
      - name: Download file
        run: aria2c -x 16 -o "${{ steps.file_name.outputs.file_name }}" "${{ github.event.inputs.url }}"
        
      - name: Create torrent using torrenttools
        run: torrenttools create -v "${{ github.event.inputs.protocol_version }}" -o "${{ github.event.inputs.name }}.torrent" -w "${{ github.event.inputs.url }}" -c "${{ github.event.inputs.comment }}" -l "${{ github.event.inputs.piece_size }}" -s "psn-pkg-torrents" "${{ steps.file_name.outputs.file_name }}"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.name }}
          path: ${{ github.event.inputs.name }}.torrent