name: Create PKG torrent
on:
  workflow_dispatch:
    inputs:
      title:
        description: Title
        required: true
      region:
        description: Region
        required: true
        default: US
        type: choice
        options: [US, EU, JP, ASIA]
      console:
        description: Console
        required: true
        default: PS3
        type: choice
        options: [PS3, PSVita, PSP]
      title-id:
        description: Title ID
        required: true
      pkg-url:
        description: PKG URL
        required: true
      protocol_version:
        description: BitTorrent Protocol version 1, 2, or hybrid
        required: true
        default: 1
        type: choice
        options: [1, 2, hybrid]
      no_commit:
        description: Don't commit torrent
        type: boolean
        
jobs:
  create_torrent:
    runs-on: ubuntu-latest
    steps:
      - name: Setup torrenttools
        uses: AnimMouse/setup-appimage@v1
        with:
          name: torrenttools
          url: https://github.com/fbdtemme/torrenttools/releases/download/v0.6.2/torrenttools-0.6.2-linux-x86_64.AppImage
          
      - name: Checkout PSN PKG Torrents
        uses: actions/checkout@v5
        with:
          path: psn-pkg-torrents
          
      - name: Get info and file name
        id: info
        run: |
          echo "info=${{ inputs.title }} ${{ inputs.region }} ${{ inputs.console }} ${{ inputs.title-id }}" >> $GITHUB_OUTPUT
          echo "file_name=$(basename ${{ inputs.pkg-url }})" >> $GITHUB_OUTPUT
          
      - name: Download PKG
        run: aria2c -x 16 -o "${{ steps.info.outputs.file_name }}" "${{ inputs.pkg-url }}"
        
      - name: Create torrent using torrenttools
        run: >
          torrenttools create -v "${{ inputs.protocol_version }}"
          -o "psn-pkg-torrents/${{ inputs.console }}/${{ steps.info.outputs.info }}.torrent" -w "${{ inputs.pkg-url }}"
          -c "${{ steps.info.outputs.info }} PSN PKG NPS by AnimMouse"
          -s psn-pkg-torrents "${{ steps.info.outputs.file_name }}"
          
      - name: Add and commit torrent
        if: '! inputs.no_commit'
        uses: EndBug/add-and-commit@v9
        with:
          add: '"${{ inputs.console }}/${{ steps.info.outputs.info }}.torrent"'
          cwd: psn-pkg-torrents
          default_author: github_actions
          message: Add ${{ inputs.title }}
          
      - name: Upload torrent
        if: inputs.no_commit
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.info.outputs.info }}
          path: psn-pkg-torrents/${{ inputs.console }}/${{ steps.info.outputs.info }}.torrent